In [4]:
import pandas as pd

df = pd.read_csv('ratings.csv', header = 0, delimiter=',')
print (df)

          userId  movieId  rating   timestamp
0              1        2     3.5  1112486027
1              1       29     3.5  1112484676
2              1       32     3.5  1112484819
3              1       47     3.5  1112484727
4              1       50     3.5  1112484580
5              1      112     3.5  1094785740
6              1      151     4.0  1094785734
7              1      223     4.0  1112485573
8              1      253     4.0  1112484940
9              1      260     4.0  1112484826
10             1      293     4.0  1112484703
11             1      296     4.0  1112484767
12             1      318     4.0  1112484798
13             1      337     3.5  1094785709
14             1      367     3.5  1112485980
15             1      541     4.0  1112484603
16             1      589     3.5  1112485557
17             1      593     3.5  1112484661
18             1      653     3.0  1094785691
19             1      919     3.5  1094785621
20             1      924     3.5  1094785598
21             1     1009     3.5  1112486013
22             1     1036     4.0  1112485480
23             1     1079     4.0  1094785665
24             1     1080     3.5  1112485375
25             1     1089     3.5  1112484669
26             1     1090     4.0  1112485453
27             1     1097     4.0  1112485701
28             1     1136     3.5  1112484609
29             1     1193     3.5  1112484690
...          ...      ...     ...         ...
20000233  138493    50872     3.5  1256750388
20000234  138493    51086     3.5  1255810566
20000235  138493    51662     4.5  1255856908
20000236  138493    51884     4.5  1256294768
20000237  138493    52579     4.0  1255856957
20000238  138493    52975     4.0  1256680293
20000239  138493    53123     4.0  1255816320
20000240  138493    53125     3.0  1255810649
20000241  138493    53322     4.0  1255812146
20000242  138493    53464     4.0  1260209920
20000243  138493    53996     4.5  1259865104
20000244  138493    55269     5.0  1255816088
20000245  138493    55814     5.0  1255811181
20000246  138493    56757     3.0  1255810698
20000247  138493    56801     3.0  1255809988
20000248  138493    58879     4.5  1255816798
20000249  138493    59315     4.0  1255818138
20000250  138493    59725     3.0  1255818078
20000251  138493    59784     5.0  1255816901
20000252  138493    60069     4.0  1258134687
20000253  138493    60816     4.5  1259865163
20000254  138493    61160     4.0  1258390537
20000255  138493    65682     4.5  1255816373
20000256  138493    66762     4.5  1255805408
20000257  138493    68319     4.5  1260209720
20000258  138493    68954     4.5  1258126920
20000259  138493    69526     4.5  1259865108
20000260  138493    69644     3.0  1260209457
20000261  138493    70286     5.0  1258126944
20000262  138493    71619     2.5  1255811136

[20000263 rows x 4 columns]

In [5]:
list(df)

['userId', 'movieId', 'rating', 'timestamp']

In [13]:
df1 = df.drop(df.columns[[2, 3]], axis = 1).drop(df.index[101:20000263])
print (df1)

     userId  movieId
0         1        2
1         1       29
2         1       32
3         1       47
4         1       50
5         1      112
6         1      151
7         1      223
8         1      253
9         1      260
10        1      293
11        1      296
12        1      318
13        1      337
14        1      367
15        1      541
16        1      589
17        1      593
18        1      653
19        1      919
20        1      924
21        1     1009
22        1     1036
23        1     1079
24        1     1080
25        1     1089
26        1     1090
27        1     1097
28        1     1136
29        1     1193
..      ...      ...
71        1     2138
72        1     2140
73        1     2143
74        1     2173
75        1     2174
76        1     2193
77        1     2194
78        1     2253
79        1     2288
80        1     2291
81        1     2542
82        1     2628
83        1     2644
84        1     2648
85        1     2664
86        1     2683
87        1     2692
88        1     2716
89        1     2761
90        1     2762
91        1     2804
92        1     2872
93        1     2918
94        1     2944
95        1     2947
96        1     2959
97        1     2968
98        1     3000
99        1     3030
100       1     3037

[101 rows x 2 columns]